// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/focusflow-redesign/Defense.tsx": () => import("../components/mockups/focusflow-redesign/Defense.tsx"),
  "./components/mockups/focusflow-redesign/Focus.tsx": () => import("../components/mockups/focusflow-redesign/Focus.tsx"),
  "./components/mockups/focusflow-redesign/Insights.tsx": () => import("../components/mockups/focusflow-redesign/Insights.tsx"),
  "./components/mockups/focusflow-redesign/Onboarding.tsx": () => import("../components/mockups/focusflow-redesign/Onboarding.tsx"),
  "./components/mockups/focusflow-redesign/Today.tsx": () => import("../components/mockups/focusflow-redesign/Today.tsx")
};
