package com.tbtechs.focusflow.ui.common

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Refresh
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import com.tbtechs.focusflow.domain.PinReuseTracker
import kotlinx.coroutines.launch

@Composable
fun PinRotationModal(
    visible: Boolean,
    pinType: PinType,
    reuseKey: PinReuseTracker.ReuseTrackerKey,
    actionLabel: String,
    actionDescription: String,
    reuseInfo: PinReuseTracker.ReuseInfo,
    onKeepSame: () -> Boolean,
    onSaveNew: suspend (String) -> Boolean,
    onComplete: () -> Unit,
    onCancel: () -> Unit,
) {
    if (!visible) return
    val scope = rememberCoroutineScope()
    var mode by remember(visible) { mutableStateOf("choose") }
    var password by remember(visible) { mutableStateOf("") }
    var confirmation by remember(visible) { mutableStateOf("") }
    var generated by remember(visible) { mutableStateOf(rotationPassword()) }
    var acknowledged by remember(visible) { mutableStateOf(false) }
    var showPassword by remember { mutableStateOf(false) }
    var showConfirmation by remember { mutableStateOf(false) }
    var saving by remember { mutableStateOf(false) }
    var error by remember { mutableStateOf<String?>(null) }

    fun saveNew(raw: String) {
        when {
            raw.length < 8 -> { error = "Password must be at least 8 characters."; return }
            mode == "custom" && raw != confirmation -> { error = "Passwords do not match."; return }
            COMMON_PASSWORDS.contains(raw.lowercase()) -> {
                error = "This password is too common — choose something unique."
                return
            }
        }
        scope.launch {
            saving = true
            val saved = runCatching { onSaveNew(raw) }.getOrDefault(false)
            saving = false
            if (saved) onComplete() else error = "Could not save the new password."
        }
    }

    AlertDialog(
        onDismissRequest = onCancel,
        title = { Text(actionLabel) },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Text(actionDescription, style = MaterialTheme.typography.bodySmall)
                when (mode) {
                    "choose" -> {
                        Text("Choose the password that will protect this action.")
                        Button(
                            enabled = reuseInfo.canReuse && !saving,
                            onClick = {
                                if (onKeepSame()) onComplete()
                                else error = "The daily reuse limit has been reached."
                            },
                        ) {
                            Text("Keep same password (${PinReuseTracker.MAX_DAILY_REUSES - reuseInfo.count} of ${PinReuseTracker.MAX_DAILY_REUSES} reuses remaining today)")
                        }
                        Button(onClick = { mode = "custom"; error = null }) { Text("Set new password") }
                        Button(onClick = { mode = "generate"; error = null }) { Text("Auto-generate") }
                        TextButton(onClick = onComplete) { Text("Skip — proceed without changing password") }
                    }
                    "custom" -> {
                        TextButton(onClick = { mode = "choose"; error = null }) { Text("← Back") }
                        PasswordRotationField(password, "New password (8+ characters)", showPassword, { password = it; error = null }) {
                            showPassword = !showPassword
                        }
                        PasswordRotationField(confirmation, "Confirm password", showConfirmation, { confirmation = it; error = null }) {
                            showConfirmation = !showConfirmation
                        }
                        Text(passwordStrength(password), style = MaterialTheme.typography.labelSmall)
                        Button(enabled = !saving, onClick = { saveNew(password) }) {
                            if (saving) CircularProgressIndicator() else Text("Set Password & Continue")
                        }
                    }
                    else -> {
                        TextButton(onClick = { mode = "choose"; error = null }) { Text("← Back") }
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text(generated, modifier = Modifier.weight(1f), style = MaterialTheme.typography.titleMedium)
                            IconButton(onClick = { generated = rotationPassword(); acknowledged = false }) {
                                Icon(Icons.Outlined.Refresh, contentDescription = "Generate another password")
                            }
                        }
                        Text("Write this down now. Only the hash is stored; there is no recovery option.", style = MaterialTheme.typography.bodySmall)
                        androidx.compose.material3.Checkbox(checked = acknowledged, onCheckedChange = { acknowledged = it })
                        Text("I have written this password down somewhere safe", style = MaterialTheme.typography.bodySmall)
                        Button(enabled = acknowledged && !saving, onClick = { saveNew(generated) }) {
                            if (saving) CircularProgressIndicator() else Text("Save & Continue")
                        }
                    }
                }
                error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
                Text("Passwords are hashed before storage. The raw password is never saved on this device.", style = MaterialTheme.typography.labelSmall)
            }
        },
        confirmButton = {},
        dismissButton = { TextButton(onClick = onCancel) { Text("Cancel") } },
    )
}

@Composable
private fun PasswordRotationField(
    value: String,
    label: String,
    visible: Boolean,
    onValueChange: (String) -> Unit,
    onToggleVisibility: () -> Unit,
) {
    Row(verticalAlignment = Alignment.CenterVertically) {
        OutlinedTextField(
            value = value,
            onValueChange = onValueChange,
            modifier = Modifier.weight(1f),
            label = { Text(label) },
            singleLine = true,
            visualTransformation = if (visible) VisualTransformation.None else PasswordVisualTransformation(),
        )
        TextButton(onClick = onToggleVisibility) { Text(if (visible) "Hide" else "Show") }
    }
}

private fun rotationPassword(): String {
    val chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789@#!$"
    val random = java.security.SecureRandom()
    return buildString(16) { repeat(16) { append(chars[random.nextInt(chars.length)]) } }
}

private fun passwordStrength(value: String): String =
    when {
        value.isEmpty() -> "Use at least 8 characters."
        value.length < 8 -> "${value.length}/8 characters minimum"
        value.length >= 16 -> "Very strong"
        value.length >= 12 -> "Strong"
        else -> "Fair — try adding symbols or numbers"
    }

private val COMMON_PASSWORDS = setOf(
    "password", "password1", "password123", "qwerty123", "qwerty",
    "abc123def", "iloveyou1", "admin1234", "letmein1", "welcome1",
    "12345678", "123456789", "1234567890", "11111111", "00000000",
    "aaaaaaaa", "bbbbbbbb", "zxcvbnm1", "focusflow", "focusflow1",
)