package com.tbtechs.focusflow.ui.common

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.defaultMinSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Lock
import androidx.compose.material.icons.outlined.Refresh
import androidx.compose.material.icons.outlined.Visibility
import androidx.compose.material.icons.outlined.VisibilityOff
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.tbtechs.focusflow.domain.PinReuseTracker
import com.tbtechs.focusflow.ui.theme.BrandPrimary
import com.tbtechs.focusflow.ui.theme.DarkBorder
import com.tbtechs.focusflow.ui.theme.DarkCard
import com.tbtechs.focusflow.ui.theme.DarkSurfaceVariant
import com.tbtechs.focusflow.ui.theme.DarkTextMuted
import com.tbtechs.focusflow.ui.theme.DarkTextPrimary
import com.tbtechs.focusflow.ui.theme.DarkTextSecondary
import kotlinx.coroutines.launch

@Composable
fun PinRotationModal(
    visible: Boolean,
    pinType: PinType,
    reuseKey: PinReuseTracker.ReuseTrackerKey,
    actionLabel: String,
    actionDescription: String,
    reuseInfo: PinReuseTracker.ReuseInfo,
    onKeepSame: () -> Boolean,
    onSaveNew: suspend (String) -> Boolean,
    onComplete: () -> Unit,
    onCancel: () -> Unit,
) {
    if (!visible) return
    val scope = rememberCoroutineScope()
    var mode by remember(visible) { mutableStateOf("choose") }
    var password by remember(visible) { mutableStateOf("") }
    var confirmation by remember(visible) { mutableStateOf("") }
    var generated by remember(visible) { mutableStateOf(rotationPassword()) }
    var acknowledged by remember(visible) { mutableStateOf(false) }
    var showPassword by remember { mutableStateOf(false) }
    var showConfirmation by remember { mutableStateOf(false) }
    var saving by remember { mutableStateOf(false) }
    var error by remember { mutableStateOf<String?>(null) }

    fun saveNew(raw: String) {
        when {
            raw.length < 8 -> { error = "Password must be at least 8 characters."; return }
            mode == "custom" && raw != confirmation -> { error = "Passwords do not match."; return }
            COMMON_PASSWORDS.contains(raw.lowercase()) -> {
                error = "This password is too common — choose something unique."
                return
            }
        }
        scope.launch {
            saving = true
            val saved = runCatching { onSaveNew(raw) }.getOrDefault(false)
            saving = false
            if (saved) onComplete() else error = "Could not save the new password."
        }
    }

    AlertDialog(
        onDismissRequest = onCancel,
        shape = RoundedCornerShape(24.dp),
        containerColor = DarkCard,
        titleContentColor = DarkTextPrimary,
        textContentColor = DarkTextSecondary,
        icon = {
            Box(
                modifier = Modifier
                    .size(48.dp)
                    .clip(RoundedCornerShape(14.dp))
                    .background(BrandPrimary.copy(alpha = 0.15f)),
                contentAlignment = Alignment.Center,
            ) {
                Icon(
                    Icons.Outlined.Lock,
                    contentDescription = null,
                    tint = BrandPrimary,
                    modifier = Modifier.size(24.dp),
                )
            }
        },
        title = {
            Text(
                text = actionLabel,
                fontSize = 18.sp,
                fontWeight = FontWeight.Bold,
            )
        },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                Text(actionDescription, fontSize = 13.sp, lineHeight = 18.sp, color = DarkTextSecondary)
                when (mode) {
                    "choose" -> {
                        Text("Choose the password that will protect this action.", fontSize = 13.sp, color = DarkTextMuted)
                        Button(
                            enabled = reuseInfo.canReuse && !saving,
                            onClick = {
                                if (onKeepSame()) onComplete()
                                else error = "The daily reuse limit has been reached."
                            },
                            shape = RoundedCornerShape(14.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = BrandPrimary),
                            modifier = Modifier.fillMaxWidth().defaultMinSize(minHeight = 44.dp),
                        ) {
                            Text("Keep same password (${PinReuseTracker.MAX_DAILY_REUSES - reuseInfo.count} of ${PinReuseTracker.MAX_DAILY_REUSES} left)", fontWeight = FontWeight.SemiBold)
                        }
                        Button(
                            onClick = { mode = "custom"; error = null },
                            shape = RoundedCornerShape(14.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = DarkSurfaceVariant),
                            modifier = Modifier.fillMaxWidth().defaultMinSize(minHeight = 44.dp),
                        ) {
                            Text("Set new password", color = DarkTextPrimary, fontWeight = FontWeight.SemiBold)
                        }
                        Button(
                            onClick = { mode = "generate"; error = null },
                            shape = RoundedCornerShape(14.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = DarkSurfaceVariant),
                            modifier = Modifier.fillMaxWidth().defaultMinSize(minHeight = 44.dp),
                        ) {
                            Text("Auto-generate", color = DarkTextPrimary, fontWeight = FontWeight.SemiBold)
                        }
                        TextButton(
                            onClick = onComplete,
                            shape = RoundedCornerShape(14.dp),
                            modifier = Modifier.fillMaxWidth().defaultMinSize(minHeight = 44.dp),
                        ) {
                            Text("Skip — proceed without changing password", color = DarkTextSecondary)
                        }
                    }
                    "custom" -> {
                        TextButton(
                            onClick = { mode = "choose"; error = null },
                            shape = RoundedCornerShape(14.dp),
                        ) {
                            Text("← Back", color = BrandPrimary)
                        }
                        PasswordRotationField(password, "New password (8+ characters)", showPassword, { password = it; error = null }) {
                            showPassword = !showPassword
                        }
                        PasswordRotationField(confirmation, "Confirm password", showConfirmation, { confirmation = it; error = null }) {
                            showConfirmation = !showConfirmation
                        }
                        Text(passwordStrength(password), fontSize = 12.sp, color = DarkTextMuted)
                        Button(
                            enabled = !saving,
                            onClick = { saveNew(password) },
                            shape = RoundedCornerShape(14.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = BrandPrimary),
                            modifier = Modifier.fillMaxWidth().defaultMinSize(minHeight = 44.dp),
                        ) {
                            if (saving) CircularProgressIndicator(color = Color.White, modifier = Modifier.size(18.dp))
                            else Text("Set Password & Continue", fontWeight = FontWeight.SemiBold)
                        }
                    }
                    else -> {
                        TextButton(
                            onClick = { mode = "choose"; error = null },
                            shape = RoundedCornerShape(14.dp),
                        ) {
                            Text("← Back", color = BrandPrimary)
                        }
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .clip(RoundedCornerShape(14.dp))
                                .background(DarkSurfaceVariant)
                                .border(1.dp, DarkBorder, RoundedCornerShape(14.dp))
                                .padding(horizontal = 14.dp, vertical = 12.dp),
                        ) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically,
                            ) {
                                Text(
                                    text = generated,
                                    fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace,
                                    fontSize = 16.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = BrandPrimary,
                                    modifier = Modifier.weight(1f),
                                )
                                IconButton(onClick = { generated = rotationPassword(); acknowledged = false }) {
                                    Icon(
                                        Icons.Outlined.Refresh,
                                        contentDescription = "Generate another password",
                                        tint = DarkTextSecondary,
                                        modifier = Modifier.size(20.dp),
                                    )
                                }
                            }
                        }
                        Text(
                            "Write this down now. Only the hash is stored; there is no recovery option.",
                            fontSize = 12.sp,
                            lineHeight = 16.sp,
                            color = Color(0xFFFBBF24),
                        )
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            androidx.compose.material3.Checkbox(
                                checked = acknowledged,
                                onCheckedChange = { acknowledged = it },
                                colors = androidx.compose.material3.CheckboxDefaults.colors(
                                    checkedColor = BrandPrimary,
                                    uncheckedColor = DarkBorder,
                                ),
                            )
                            Text("I have saved this password somewhere safe", fontSize = 12.sp, color = DarkTextPrimary)
                        }
                        Button(
                            enabled = acknowledged && !saving,
                            onClick = { saveNew(generated) },
                            shape = RoundedCornerShape(14.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = BrandPrimary),
                            modifier = Modifier.fillMaxWidth().defaultMinSize(minHeight = 44.dp),
                        ) {
                            if (saving) CircularProgressIndicator(color = Color.White, modifier = Modifier.size(18.dp))
                            else Text("Save & Continue", fontWeight = FontWeight.SemiBold)
                        }
                    }
                }
                error?.let { Text(it, color = Color(0xFFEF4444), fontSize = 12.sp) }
                Text(
                    "Passwords are hashed before storage. The raw password is never saved on this device.",
                    fontSize = 11.sp,
                    color = DarkTextMuted,
                )
            }
        },
        confirmButton = {},
        dismissButton = {
            TextButton(
                onClick = onCancel,
                shape = RoundedCornerShape(14.dp),
                modifier = Modifier.defaultMinSize(minHeight = 44.dp),
            ) {
                Text("Cancel", color = DarkTextSecondary)
            }
        },
    )
}

@Composable
private fun PasswordRotationField(
    value: String,
    label: String,
    visible: Boolean,
    onValueChange: (String) -> Unit,
    onToggleVisibility: () -> Unit,
) {
    OutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        modifier = Modifier.fillMaxWidth(),
        placeholder = { Text(label, color = DarkTextMuted, fontSize = 13.sp) },
        singleLine = true,
        visualTransformation = if (visible) VisualTransformation.None else PasswordVisualTransformation(),
        trailingIcon = {
            IconButton(onClick = onToggleVisibility) {
                Icon(
                    if (visible) Icons.Outlined.VisibilityOff else Icons.Outlined.Visibility,
                    contentDescription = if (visible) "Hide" else "Show",
                    tint = DarkTextSecondary,
                    modifier = Modifier.size(18.dp),
                )
            }
        },
        shape = RoundedCornerShape(14.dp),
        colors = OutlinedTextFieldDefaults.colors(
            focusedContainerColor = DarkSurfaceVariant,
            unfocusedContainerColor = DarkSurfaceVariant,
            focusedBorderColor = BrandPrimary,
            unfocusedBorderColor = DarkBorder,
            focusedTextColor = DarkTextPrimary,
            unfocusedTextColor = DarkTextPrimary,
        ),
    )
}

private fun rotationPassword(): String {
    val chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789@#!$"
    val random = java.security.SecureRandom()
    return buildString(16) { repeat(16) { append(chars[random.nextInt(chars.length)]) } }
}

private fun passwordStrength(value: String): String =
    when {
        value.isEmpty() -> "Use at least 8 characters."
        value.length < 8 -> "${value.length}/8 characters minimum"
        value.length >= 16 -> "Very strong"
        value.length >= 12 -> "Strong"
        else -> "Fair — try adding symbols or numbers"
    }

private val COMMON_PASSWORDS = setOf(
    "password", "password1", "password123", "qwerty123", "qwerty",
    "abc123def", "iloveyou1", "admin1234", "letmein1", "welcome1",
    "12345678", "123456789", "1234567890", "11111111", "00000000",
    "aaaaaaaa", "bbbbbbbb", "zxcvbnm1", "focusflow", "focusflow1",
)