package com.tbtechs.focusflow.ui.common

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.defaultMinSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Check
import androidx.compose.material.icons.outlined.Key
import androidx.compose.material.icons.outlined.Refresh
import androidx.compose.material.icons.outlined.Visibility
import androidx.compose.material.icons.outlined.VisibilityOff
import androidx.compose.material.icons.outlined.Warning
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CheckboxDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.tbtechs.focusflow.ui.theme.BrandPrimary
import com.tbtechs.focusflow.ui.theme.DarkBorder
import com.tbtechs.focusflow.ui.theme.DarkCard
import com.tbtechs.focusflow.ui.theme.DarkSurfaceVariant
import com.tbtechs.focusflow.ui.theme.DarkTextMuted
import com.tbtechs.focusflow.ui.theme.DarkTextPrimary
import com.tbtechs.focusflow.ui.theme.DarkTextSecondary
import kotlinx.coroutines.launch
import java.security.SecureRandom

enum class PinType { FOCUS, DEFENSE }

/**
 * Setup modal for Focus and Defense passwords.
 *
 * Implements screenshots 3e_11 and 3e_12 with manual password and generated password tabs.
 */
@Composable
fun PinSetupModal(
    visible: Boolean,
    pinType: PinType,
    onSaved: (String) -> Boolean,
    onCancel: () -> Unit,
) {
    if (!visible) return
    val scope = rememberCoroutineScope()
    var generated by remember(visible) { mutableStateOf(randomPassword()) }
    var custom by remember(visible) { mutableStateOf(true) }
    var password by remember(visible) { mutableStateOf("") }
    var confirmation by remember(visible) { mutableStateOf("") }
    var acknowledged by remember(visible) { mutableStateOf(false) }
    var showPassword by remember { mutableStateOf(false) }
    var showConfirmation by remember { mutableStateOf(false) }
    var saving by remember { mutableStateOf(false) }
    var error by remember { mutableStateOf<String?>(null) }

    fun save(raw: String) {
        when {
            raw.length < 8 -> {
                error = "Password must be at least 8 characters."
                return
            }
            COMMON_PASSWORDS.contains(raw.lowercase()) -> {
                error = "This password is too common — choose something unique."
                return
            }
        }
        scope.launch {
            saving = true
            error = null
            val saved = runCatching { onSaved(raw) }.getOrDefault(false)
            saving = false
            if (saved) onCancel() else error = "Could not save the password. Please try again."
        }
    }

    AlertDialog(
        onDismissRequest = onCancel,
        shape = RoundedCornerShape(24.dp),
        containerColor = DarkCard,
        titleContentColor = DarkTextPrimary,
        textContentColor = DarkTextSecondary,
        icon = {
            Box(
                modifier = Modifier
                    .size(48.dp)
                    .clip(RoundedCornerShape(14.dp))
                    .background(BrandPrimary.copy(alpha = 0.15f)),
                contentAlignment = Alignment.Center,
            ) {
                Icon(
                    Icons.Outlined.Key,
                    contentDescription = null,
                    tint = BrandPrimary,
                    modifier = Modifier.size(24.dp),
                )
            }
        },
        title = {
            Text(
                text = "Set ${pinType.label} Password",
                fontSize = 18.sp,
                fontWeight = FontWeight.Bold,
            )
        },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(14.dp)) {
                Text(
                    text = pinType.description,
                    fontSize = 13.sp,
                    lineHeight = 18.sp,
                    color = DarkTextSecondary,
                )

                // Mode Selector matching 3e_11 & 3e_12
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(14.dp))
                        .background(DarkSurfaceVariant)
                        .border(1.dp, DarkBorder, RoundedCornerShape(14.dp))
                        .padding(4.dp),
                    horizontalArrangement = Arrangement.spacedBy(4.dp),
                ) {
                    Box(
                        modifier = Modifier
                            .weight(1f)
                            .clip(RoundedCornerShape(10.dp))
                            .background(if (custom) BrandPrimary else Color.Transparent)
                            .clickable { custom = true; error = null }
                            .padding(vertical = 8.dp),
                        contentAlignment = Alignment.Center,
                    ) {
                        Text(
                            text = "I'll choose",
                            fontSize = 13.sp,
                            fontWeight = if (custom) FontWeight.Bold else FontWeight.Normal,
                            color = if (custom) Color.White else DarkTextSecondary,
                        )
                    }

                    Box(
                        modifier = Modifier
                            .weight(1f)
                            .clip(RoundedCornerShape(10.dp))
                            .background(if (!custom) BrandPrimary else Color.Transparent)
                            .clickable { custom = false; error = null }
                            .padding(vertical = 8.dp),
                        contentAlignment = Alignment.Center,
                    ) {
                        Text(
                            text = "Generate for me",
                            fontSize = 13.sp,
                            fontWeight = if (!custom) FontWeight.Bold else FontWeight.Normal,
                            color = if (!custom) Color.White else DarkTextSecondary,
                        )
                    }
                }

                if (custom) {
                    // Manual entry fields matching 3e_11
                    Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                        OutlinedTextField(
                            value = password,
                            onValueChange = { password = it; error = null },
                            modifier = Modifier.fillMaxWidth(),
                            placeholder = { Text("Password (8+ characters)", color = DarkTextMuted, fontSize = 13.sp) },
                            singleLine = true,
                            visualTransformation = if (showPassword) VisualTransformation.None else PasswordVisualTransformation(),
                            trailingIcon = {
                                IconButton(onClick = { showPassword = !showPassword }) {
                                    Icon(
                                        if (showPassword) Icons.Outlined.VisibilityOff else Icons.Outlined.Visibility,
                                        contentDescription = if (showPassword) "Hide" else "Show",
                                        tint = DarkTextSecondary,
                                        modifier = Modifier.size(18.dp),
                                    )
                                }
                            },
                            shape = RoundedCornerShape(14.dp),
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedContainerColor = DarkSurfaceVariant,
                                unfocusedContainerColor = DarkSurfaceVariant,
                                focusedBorderColor = BrandPrimary,
                                unfocusedBorderColor = DarkBorder,
                                focusedTextColor = DarkTextPrimary,
                                unfocusedTextColor = DarkTextPrimary,
                            ),
                        )

                        OutlinedTextField(
                            value = confirmation,
                            onValueChange = { confirmation = it; error = null },
                            modifier = Modifier.fillMaxWidth(),
                            placeholder = { Text("Confirm password", color = DarkTextMuted, fontSize = 13.sp) },
                            singleLine = true,
                            visualTransformation = if (showConfirmation) VisualTransformation.None else PasswordVisualTransformation(),
                            trailingIcon = {
                                IconButton(onClick = { showConfirmation = !showConfirmation }) {
                                    Icon(
                                        if (showConfirmation) Icons.Outlined.VisibilityOff else Icons.Outlined.Visibility,
                                        contentDescription = if (showConfirmation) "Hide" else "Show",
                                        tint = DarkTextSecondary,
                                        modifier = Modifier.size(18.dp),
                                    )
                                }
                            },
                            shape = RoundedCornerShape(14.dp),
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedContainerColor = DarkSurfaceVariant,
                                unfocusedContainerColor = DarkSurfaceVariant,
                                focusedBorderColor = BrandPrimary,
                                unfocusedBorderColor = DarkBorder,
                                focusedTextColor = DarkTextPrimary,
                                unfocusedTextColor = DarkTextPrimary,
                            ),
                        )

                        if (confirmation.isNotEmpty() && password != confirmation) {
                            Text("Passwords do not match", color = Color(0xFFEF4444), fontSize = 12.sp)
                        }

                        if (password.isNotEmpty()) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically,
                            ) {
                                Text(
                                    text = passwordStrength(password),
                                    fontSize = 12.sp,
                                    color = if (password.length >= 8) Color(0xFF34D399) else Color(0xFFFBBF24),
                                )
                                Text(
                                    text = "${password.length} chars",
                                    fontSize = 12.sp,
                                    color = DarkTextMuted,
                                )
                            }
                        }
                    }
                } else {
                    // Generated password card matching 3e_12
                    Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .clip(RoundedCornerShape(14.dp))
                                .background(DarkSurfaceVariant)
                                .border(1.dp, DarkBorder, RoundedCornerShape(14.dp))
                                .padding(horizontal = 14.dp, vertical = 12.dp),
                        ) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically,
                            ) {
                                Text(
                                    text = generated,
                                    fontFamily = FontFamily.Monospace,
                                    fontSize = 16.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = BrandPrimary,
                                    modifier = Modifier.weight(1f),
                                )
                                IconButton(onClick = {
                                    generated = randomPassword()
                                    acknowledged = false
                                    error = null
                                }) {
                                    Icon(
                                        Icons.Outlined.Refresh,
                                        contentDescription = "Generate another",
                                        tint = DarkTextSecondary,
                                        modifier = Modifier.size(20.dp),
                                    )
                                }
                            }
                        }

                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .clip(RoundedCornerShape(14.dp))
                                .background(Color(0xFF451A03))
                                .border(1.dp, Color(0xFFF59E0B).copy(alpha = 0.4f), RoundedCornerShape(14.dp))
                                .padding(12.dp),
                        ) {
                            Row(
                                verticalAlignment = Alignment.Top,
                                horizontalArrangement = Arrangement.spacedBy(8.dp),
                            ) {
                                Icon(Icons.Outlined.Warning, contentDescription = null, tint = Color(0xFFF59E0B), modifier = Modifier.size(16.dp))
                                Text(
                                    "Write this down now. Only the cryptographic hash is stored; there is no recovery option.",
                                    fontSize = 12.sp,
                                    lineHeight = 16.sp,
                                    color = Color(0xFFFBBF24),
                                )
                            }
                        }

                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            modifier = Modifier.clickable { acknowledged = !acknowledged; error = null },
                        ) {
                            Checkbox(
                                checked = acknowledged,
                                onCheckedChange = { acknowledged = it; error = null },
                                colors = CheckboxDefaults.colors(
                                    checkedColor = BrandPrimary,
                                    uncheckedColor = DarkBorder,
                                ),
                            )
                            Text(
                                "I have saved this password somewhere safe",
                                fontSize = 12.sp,
                                color = DarkTextPrimary,
                            )
                        }
                    }
                }

                error?.let {
                    Text(it, color = Color(0xFFEF4444), fontSize = 12.sp)
                }
            }
        },
        confirmButton = {
            Button(
                enabled = !saving,
                onClick = {
                    when {
                        custom && password != confirmation -> error = "Passwords do not match."
                        custom -> save(password)
                        !acknowledged -> error = "Confirm you have saved this password before continuing."
                        else -> save(generated)
                    }
                },
                colors = ButtonDefaults.buttonColors(containerColor = BrandPrimary),
                shape = RoundedCornerShape(14.dp),
                modifier = Modifier.defaultMinSize(minHeight = 44.dp),
            ) {
                if (saving) {
                    CircularProgressIndicator(color = Color.White, modifier = Modifier.size(16.dp))
                } else {
                    Text(
                        if (custom) "Set Password" else "Save Generated Password",
                        fontWeight = FontWeight.SemiBold,
                        color = Color.White,
                    )
                }
            }
        },
        dismissButton = {
            TextButton(
                onClick = onCancel,
                shape = RoundedCornerShape(14.dp),
                modifier = Modifier.defaultMinSize(minHeight = 44.dp),
            ) {
                Text("Cancel", color = DarkTextSecondary)
            }
        },
    )
}

private val PinType.label: String
    get() = if (this == PinType.FOCUS) "Focus Session" else "Defense"

private val PinType.description: String
    get() = if (this == PinType.FOCUS) {
        "Required to end an active focus session early. Store it somewhere accessible."
    } else {
        "Required before disabling protection, clearing block lists, or removing restrictions."
    }

private val COMMON_PASSWORDS = setOf(
    "password", "password1", "password123", "qwerty123", "qwerty",
    "abc123def", "iloveyou1", "admin1234", "letmein1", "welcome1",
    "12345678", "123456789", "1234567890", "11111111", "00000000",
    "aaaaaaaa", "bbbbbbbb", "zxcvbnm1", "focusflow", "focusflow1",
)

private fun passwordStrength(value: String): String {
    if (value.isEmpty()) return "Use at least 8 characters."
    if (value.length < 8) return "${value.length}/8 characters minimum"
    val variety = listOf(
        value.any { it.isUpperCase() },
        value.any { it.isLowerCase() },
        value.any { it.isDigit() },
        value.any { !it.isLetterOrDigit() },
    ).count { it }
    return when {
        value.length >= 16 && variety >= 3 -> "Very strong password ✓"
        value.length >= 12 && variety >= 2 -> "Strong password ✓"
        variety >= 2 -> "Fair — consider adding symbols or numbers"
        else -> "Weak — mix uppercase, numbers and symbols"
    }
}

private fun randomPassword(length: Int = 16): String {
    val chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789@#!$"
    val random = SecureRandom()
    return buildString(length) { repeat(length) { append(chars[random.nextInt(chars.length)]) } }
}
